apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: gpt2-cpu
  namespace: default
 
spec:
  annotations:
    prometheus.io/scrape: "true" 
    prometheus.io/path: "/prometheus" 
    prometheus.io/port: "8000"
  protocol: v2
  predictors:
  - name: default
    replicas: 1
    graph:
      name: transformer
      implementation: HUGGINGFACE_SERVER
      parameters:
      - name: task
        type: STRING
        value: text-generation
      - name: batch_size
        type: INT
        value: "128"
    componentSpecs:
     - spec:
         containers:
         - name: transformer
           env:
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
           resources:
             requests:
               memory: 6Gi
               cpu: 2
