apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: gpt2-model
  namespace: default
spec:
  protocol: v2
  predictors:
  - name: default
    replicas: 1
    graph:
      name: transformer
      implementation: HUGGINGFACE_SERVER
      parameters:
      - name: task
        type: STRING
        value: text-generation
      - name: pretrained_model
        type: STRING
        value: distilgpt2
      - name: optimum_model
        type: BOOL
        value: true   
    componentSpecs:
     - spec:
        containers:
        - name: transformer
          resources:
            requests:
              memory: 2Gi
              cpu: 2
              nvidia.com/gpu: 1    
            limits:
              memory: 4Gi
              cpu: 4
              nvidia.com/gpu: 1  
        tolerations:
          - key: "sku"          # to be able to run  in GPU Nodepool
            operator: "Equal"
            value: "gpu"
            effect: "NoSchedule"        


     