apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: gpt2-cpu
  namespace: default
spec:
  protocol: v2
  predictors:
  - name: default
    replicas: 1
    graph:
      name: transformer
      implementation: HUGGINGFACE_SERVER
      parameters:
      - name: task
        type: STRING
        value: text-generation
      - name: batch_size
        type: INT
        value: "128"