apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: gpt2-gpu
  namespace: default
spec:
  protocol: v2
  annotations:
    prometheus.io/scrape: "true" 
    prometheus.io/path: "/prometheus" 
    prometheus.io/port: "8000"
  predictors:
  - name: default
    replicas: 1
    graph:
      name: transformer
      implementation: HUGGINGFACE_SERVER
      parameters:
      - name: task
        type: STRING
        value: text-generation
      - name: pretrained_model
        type: STRING
        value: distilgpt2 
      - name: device
        type: INT
        value: "0"
      - name: batch_size
        type: INT
        value: "128"  
    componentSpecs:
     - spec:
         containers:
         - name: transformer
           env:
          - name: MLSERVER_PARALLEL_WORKERS
            value: "0"
          - name: MLSERVER_MODEL_MAX_BATCH_SIZE
            value: "128"
          - name: MLSERVER_MODEL_MAX_BATCH_TIME
            value: "1"
           resources:
             requests:
               memory: 6Gi
               cpu: 2
               nvidia.com/gpu: 1    
             limits:
               cpu: 4
               nvidia.com/gpu: 1  
           securityContext:
             runAsUser: 0    
         tolerations:
           - key: "sku"          # to be able to run  in GPU Nodepool
             operator: "Equal"
             value: "gpu"
             effect: "NoSchedule"        
        

     
